SET "PINGERLOD_PROJECT_HOME=C:/Users/Renan/Dropbox/PendriveOnline/workspace/PingERETL"
SET "PINGERLOD_LIB=%PINGERLOD_PROJECT_HOME%/lib"
SET "PINGERLOD_SRC=%PINGERLOD_PROJECT_HOME%/src"
SET "PINGERLOD_BIN=%PINGERLOD_PROJECT_HOME%/bin"

SET "PINGERLOD_CP=%PINGERLOD_LIB%/*"
SET "PINGERLOD_MAINCLASS=%PINGERLOD_SRC%/edu/stanford/slac/pinger/main/GetPingtableCSV.java"
SET "PINGERLOD_MAINCOMPILEDCLASS=edu.stanford.slac.pinger.main.GetPingtableCSV"